#version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./test-files:/home/
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: Kas9ya!@
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    env_file:
      - sqlserver.env
      - sapassword.env
    command: >
      bash -c "/opt/mssql/bin/sqlservr
      && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Ka9ya!@ -q \"CREATE DATABASE nvssmessaging;\""
    
