name: Run Test Suite on PR or push to main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    services:
      sql.data:
        image: postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
      - "5432:5432"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Test 1
      run: dotnet test --filter GetMessageStatus_ReturnsMessages
    - name: Test 2
      run: dotnet test --filter PostRecord_ShouldSaveMessage